---
- name: Ansible Collection
  include_role:
    name: managed_ansible_collection
  vars:
    collection_name: "{{ project.collection_name }}"
    collection_namespace: "{{ project.collection_namespace }}"
    collection_subdir: "{{ project.collection_subdir | default('',true) }}"
    depth: "{{ project.depth | default(false, true) }}"
    single_branch: "{{ project.single_branch | default(false, true) }}"
    git_url: "{{ project.git_url }}"
  loop: "{{ managed_ansible_collections }}"
  loop_control:
    label: "{{ project.git_url }}"
    loop_var: project
  when:
  - managed_ansible_collections is defined and managed_ansible_collections is iterable
