---
- name: Perform safe-purge of git repos at {{ managed_ansible_collections_path }}
  include_role:
    name: korbad.project_management.managed_git_repos
    with_tasks: safe_purge.yml
  vars:
    managed_git_repos_path: "{{ managed_ansible_collections_path }}"