- name: Query user for information
  include_role:
    name: korbad.vars.prompt_terminal_for_user_fact
  vars:
    managed_user_var: "{{ managed_user_local_var_name }}"
  when: 
  - managed_user_local_var_value is undefined

- name: Create var file
  ansible.builtin.copy:
    content: "{{ managed_user_local_var_value }}"
    dest: "{{ managed_user_local_var_path }}"
    mode: u+rw,og-rwx
  vars:
    managed_user_local_var_value: "{{ vars[managed_user_local_var_name] }}"
