---
argument_specs:
  main:
    options:
      collection_name:
        type: str
      collection_namespace:
        type: str
      project_path:
        type: str
      source_path:
        type: str
  collection_list:
    options:
      managed_ansible_collections_list:
        type: list
        required: true
  