- name: Query user for information
  include_role:
    name: korbad.secrets.prompt_user
  when: 
  - managed_secret_type|default("generated", true) == "user"
  - managed_secret_value is undefined

- name: Create secret file
  ansible.builtin.copy:
    content: "{{ managed_secret_value | default(generated_pw, true) }}"
    dest: "{{ managed_secret_path }}"
    mode: u+rw,og-rwx
  no_log: true
  vars:
    managed_secret_value: "{{ vars[managed_secret_name] }}"
    generated_pw: "{{ lookup('ansible.builtin.password', '/dev/null') }}"

- name: Encrypt (ansible-vault) managed secret {{ managed_secret_path }}
  command:
    cmd: ansible-vault encrypt {{ managed_secret_path }} --vault-password-file {{ vault_password_file_path }}