- name: Ensure managed_secrets directory exists {{ managed_secrets_path }}
  file:
    state: directory
    path: "{{ managed_secrets_path }}"
    recurse: yes

- name: Create secret file
  ansible.builtin.copy:
    content: "{{ managed_secret_value }}"
    dest: "{{ managed_secret_path }}"
    mode: u+rw,og-rwx
  no_log: true

- name: Encrypt (ansible-vault) managed secret {{ managed_secret_path }}
  command:
    cmd: ansible-vault encrypt {{ managed_secret_path }}