---
- name: Managed secret stat {{ managed_secret_path }}
  stat:
    path: "{{ managed_secret_path }}"
  register: managed_secret

- name: Create secret file if it doesn't exist
  include_tasks: create_and_encrypt.yml
  when: not managed_secret.stat.exists or managed_secret_overwrite|default(false,true)|bool
  
- name: Ensure fact exists with managed secret value
  set_fact:
    "{{ managed_secret_name }}": "{{ lookup('file', managed_secret_path) }}"
