---
- name: Get git status {{ source_path }}
  command:
    cmd: git status
    chdir: "{{ source_path }}"
  register: git_status

- name: Set unstaged/untracked facts
  set_fact:
    unstaged_changes_detected: "{{ 'Changes not staged for commit' in git_status.stdout }}"
    untracked_files_detected: "{{ 'Untracked files' in git_status.stdout }}"