---
- hosts: localhost
  vars_prompt:
  - name: git_url
    prompt: git url of ansible vars?
  - name: managed_git_repo_dirname
    prompt: managed_git_repo_dirname?
  vars:
    current_user: "{{ lookup('env','USER') }}"
  roles:
  - name: korbad.project_management.managed_git_repo
  - name: korbad.project_management.load_vars_from_path
    vars:
      load_vars_path: "{{ managed_git_repo_path }}"
  - name: korbad.project_management.managed_ansible_collections
  - name: korbad.project_management.managed_ansible_roles
  - name: korbad.project_management.managed_git_repos