---
- name: Safely purge managed_git_repos_path of git repos for current user on localhost
  hosts: localhost
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_connection: local
  tasks:
  - name: Safely purge all managed git repos
    include_role:
      name: managed_git_repos
      tasks_from: safe_purge
