---
- name: Purge symlinks from collection source
  include_tasks: purge_symlinks.yml

- name: Ensure collection namespace directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ (collections_path, 'ansible_collections', collection_namespace) | path_join }}"

- name: Ensure symlink exists between collection project directory and ansible collections path
  ansible.builtin.file:
    path: "{{ collection_path }}"
    state: link
    src: "{{ source_path }}"
    force: yes
  vars:
    collection_path: "{{ (collections_path, 'ansible_collections', collection_namespace, collection_name) | path_join }}"
    