---
- name: For each role in ansible_roles_list, execute 'ansible_role' role
  include_role:
    name: ansible_role
  loop: "{{ ansible_roles_list }}"
  loop_control:
    label: "{{ role.git_url }}"
    loop_var: role
  vars:
    git_url: "{{ role.git_url }}"
    fully_qualified_role_name: "{{ role.fully_qualified_role_name }}"
  when: ansible_roles_list is defined and ansible_roles_list is iterable and fully_qualified_role_name is defined
