---
- name: Ensure the src directory exists for git repo {{ managed_git_repo_path }}
  file:
    state: directory
    path: "{{ managed_git_repo_path }}"

- name: Ensure clone of remote repo exists locally for giturl {{ git_url }}
  ansible.builtin.git:
    dest: "{{ managed_git_repo_path }}"
    repo: "{{ git_url }}"
    force: false
    update: false
    version: "{{ version | default(omit, true) }}"
    recursive: false
    depth: "{{ depth | default(omit, true) }}"
    single_branch: "{{ single_branch | default(omit, true) }}"
