---
- name: Create directory for project's virtual environment
  file:
    state: directory
    path: "{{ managed_project_venv_path }}"

- name: Create venv at {{ managed_project_venv_path }}
  pip:
    requirements: "{{ (managed_project_path, 'requirements.txt') | path_join }}"
    state: present
    virtualenv: "{{ managed_project_venv_path }}"
    virtualenv_site_packages: no
    virtualenv_python: python3.8
