---
- name: Create directory for container
  file:
    state: directory
    path: "{{ container_path }}"

- name: Create image from {{ containerfile_path }} for {{ container_name}}
  containers.podman.podman_image:
    path: "{{ containerfile_path | dirname }}"
    name: "{{ image_name }}"
    # force: true

- name: Ensure container is running for {{ containerfile_path }}
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    entrypoint: "{{ container_entrypoint | default(omit,true) }}"
    interactive: true
    detach: true