---
- name: Get ansible_user_vars_git_url from local user vars
  include_role:
    name: korbad.project_management.managed_user_local_var
  vars:
    managed_user_local_var_name: ansible_user_vars_git_url

- name: Ensure user vars repo exists
  include_role:
    name: managed_ansible_vars_repo
  vars:
    managed_git_repo_path: "{{ managed_user_vars_directory_path }}"
    git_url: "{{ ansible_user_vars_git_url }}"
    git_pull: true