- name: Query user for information
  include_role:
    name: korbad.vars.prompt_terminal_for_user_fact
  when: 
  - managed_var_value is undefined

- name: Create var file
  ansible.builtin.copy:
    content: "{{ managed_var_value }}"
    dest: "{{ managed_var_path }}"
    mode: u+rw,og-rwx
  vars:
    managed_var_value: "{{ vars[managed_var_name] }}"
