---
- name: For each collection in managed_ansible_collections_list, execute 'managed_ansible_collection' role
  include_tasks: main.yml
  loop: "{{ managed_ansible_collections_list }}"
  loop_control:
    label: "{{ collection.git_url }}"
    loop_var: collection
  vars:
    git_url: "{{ collection.git_url }}"
    collection_name: "{{ collection.collection_name }}"
    collection_namespace: "{{ collection.collection_namespace }}"
  when: managed_ansible_collections_list is defined and managed_ansible_collections_list is iterable