---
- name: git diff for branch {{ branch }}
  command:
    cmd: git diff {{ branch }} origin/{{ branch }} --numstat
    chdir: "{{ source_path }}"
  register: git_diff
  failed_when: false

- name: Update branch dict
  set_fact:
    branches_dict: "{{ branches_dict | default({}, True) | combine({key: val}) }}"
    branches_git_diff_complaints: "{{ branches_git_diff_complaints | default({}, True) | combine({key: git_diff_complained})}}"
  vars:
    key: "{{ branch }}"
    val: "{{ git_diff.stdout_lines | length }}"
    git_diff_complained: "{{ (git_diff.stdout | length > 0) or (git_diff.stderr | length > 0) or (git_diff.rc != 0) }}"
