---
- name: Venv setup for Archlinux
  include_role:
    name: managed_ansible_virtual_environment/arch
  when: ansible_distribution == 'Archlinux'

- name: Venv setup for AlmaLinux
  include_role:
    name: managed_ansible_virtual_environment/alma
  when: ansible_distribution == 'AlmaLinux'

- name: Venv setup for Ubuntu
  include_role:
    name: managed_ansible_virtual_environment/ubuntu
  when: ansible_distribution == 'Ubuntu'

- name: Set up venv
  include_tasks: manage_venv.yml