---
- name: Managed file stat {{ vault_password_file_path }}
  stat:
    path: "{{ vault_password_file_path }}"
  register: managed_vault_password_file
  
- name: Create random vault password file if one doesn't exist
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits,punctuation') }}"
    dest: "{{ vault_password_file_path }}"
    mode: u+rw,og-rwx
  when:
  - not managed_vault_password_file.stat.exists

- name: Ensure file has the correct permissions
  ansible.builtin.file:
    path: "{{ vault_password_file_path }}"
    state: file
    mode: u=rw,g-rwx,o-rwx