---
- name: Manage role meta directory
  file:
    state: directory
    recurse: yes
    path: "{{ managed_role_path }}/meta"

- name: Manage role meta/main.yml
  template:
    dest: "{{ managed_role_path }}/meta/main.yml"
    src: templates/meta_main.yml.j2

- name: Manage role README.md
  template:
    dest: "{{ managed_role_path }}/README.md"
    src: templates/README.md.j2
