---
- name: Create directory for SSL files
  ansible.builtin.file:
    path: "{{ managed_k8s_ssl_dir }}"
    state: directory
    mode: 0755

- name: Generate CA key
  community.crypto.openssl_privatekey:
    path: "{{ managed_k8s_ca_key }}"
    size: "{{ managed_k8s_ca_key_size }}"

- name: Generate CA CSR
  community.crypto.openssl_csr:
    path: "{{ managed_k8s_ca_csr }}"
    privatekey_path: "{{ managed_k8s_ca_key }}"
    subject:
      commonName: "{{ managed_k8s_ca_common_name }}"

- name: Generate CA certificate
  community.crypto.x509_certificate:
    path: "{{ managed_k8s_ca_crt }}"
    privatekey_path: "{{ managed_k8s_ca_key }}"
    csr_path: "{{ managed_k8s_ca_csr }}"
    provider: selfsigned

- name: Generate client key
  community.crypto.openssl_privatekey:
    path: "{{ managed_k8s_client_key }}"
    size: "{{ managed_k8s_client_key_size }}"

- name: Generate client CSR
  community.crypto.openssl_csr:
    path: "{{ managed_k8s_client_csr }}"
    privatekey_path: "{{ managed_k8s_client_key }}"
    subject:
      commonName: "{{ managed_k8s_ca_common_name }}"

- name: Generate client certificate
  community.crypto.x509_certificate:
    path: "{{ managed_k8s_client_crt }}"
    privatekey_path: "{{ managed_k8s_client_key }}"
    csr_path: "{{ managed_k8s_client_csr }}"
    provider: ownca
    ownca_path: "{{ managed_k8s_ca_crt }}"
    ownca_privatekey_path: "{{ managed_k8s_ca_key }}"
