---
- name: Ensure git repo exists
  include_tasks: ansible_collection_work.yml
  vars:
    project_name: "ansible-collection_{{ collection_namespace }}.{{ collection_name }}"
    project_path: "{{ (managed_projects_path, project_name) | path_join }}"
    collections_path: "{{ (ansible_env.HOME, '.ansible', 'collections') | path_join }}"