---
- name: Ansible Collection
  include_tasks: ansible_collection.yml
  vars:
    collection_name: "{{ project.collection_name }}"
    collection_namespace: "{{ project.collection_namespace }}"
  when:
  - project.collection_name is defined
  - project.collection_namespace is defined

- name: Ansible Role
  include_tasks: ansible_role.yml
  vars:
    fully_qualified_role_name: "{{ project.fully_qualified_role_name }}"
  when:
  - project.fully_qualified_role_name is defined

- name: Generic Project
  include_tasks: git_repo.yml
  vars:
    project_name: "{{ project.project_name }}"
  when:
  - project.project_name is defined
