---

- name: Ensure the src directory exists for git repo {{ managed_project_manager_path }}
  file:
    state: directory
    path: "{{ managed_project_manager_path }}"

- name: Ensure clone of remote repo exists locally for giturl {{ project_manager_git_url }}
  ansible.builtin.git:
    dest: "{{ managed_project_manager_path }}"
    repo: "{{ project_manager_git_url }}"
    force: true
    update: true

- name: Ensure managed clone of git repo exists for korbad.project_management collection (this collection)
  include_role:
    name: managed_ansible_collection
  vars:
    git_url: "{{ project_manager_git_url }}"
    collection_namespace: korbad
    collection_name: project_management
    managed_ansible_collections_dirname: "{{ managed_project_manager_dirname }}"
