---
- name: git repo
  include_tasks: single_repo.yml
  loop: "{{ lookup('ansible.builtin.dict', managed_git_repos, wantlist=True) }}"
  vars:
    managed_git_repo_dirname: "{{ project.key }}"
    depth: "{{ project.value.depth | default(false, true) }}"
    single_branch: "{{ project.value.single_branch | default(false, true) }}"
    git_url: "{{ project.value.git_url }}"
    managed_git_repo_path: "{{ (managed_git_repos_path, managed_git_repo_dirname) | path_join }}"
  loop_control:
    label: "{{ project.value.git_url }}"
    loop_var: project
  when:
  - managed_git_repos is defined and managed_git_repos is iterable
