---
- name: git repo
  include_role:
    name: managed_git_repo
  loop: "{{ lookup('ansible.builtin.dict', managed_git_repos) }}"
  vars:
    managed_git_repo_dirname: "{{ project.value.project_name | default(false, true) }}"
    depth: "{{ project.value.depth | default(false, true) }}"
    single_branch: "{{ project.value.single_branch | default(false, true) }}"
    git_url: "{{ project.value.git_url }}"
  loop_control:
    label: "{{ project.value.git_url }}"
    loop_var: project
  when:
  - managed_git_repos is defined and managed_git_repos is iterable
