---
- name: Check entire repo before purge
  include_tasks: checks/repo.yml

- name: PURGE {{ source_path }}
  file:
    state: absent
    path: "{{ source_path }}"
  when:
  - not unstaged_changes_detected
  - not untracked_files_detected
  - not git_stash_detected
  - unpublished_changes_sum | int == 0
  - not any_git_diff_complaints
