---
- name: "Ensure clone of remote repo exists locally for giturl {{ git_url }}"
  ansible.builtin.git:
    dest: "{{ managed_git_repo_path }}"
    repo: "{{ git_url }}"
    force: false
    update: "{{ git_pull | default(false, true) }}"
    version: "{{ version | default(omit, true) }}"
    recursive: false
    depth: "{{ depth | default(omit, true) }}"
    single_branch: "{{ single_branch | default(omit, true) }}"
    key_file: "{{ git_ssh_key_file_path | default(omit, true) }}"
    accept_hostkey: true
  register: git_module_result
