---
- name: Check for git stash
  command:
    cmd: git stash list
    chdir: "{{ source_path }}"
  register: git_stash

- name: Set fact for git_stash
  set_fact:
    git_stash_detected: "{{ git_stash.stdout | length > 0 }}"