---
- name: Ensure the src directory exists for git repo {{ managed_ansible_vars_repo_path }}
  file:
    state: directory
    path: "{{ managed_ansible_vars_repo_path }}"

- name: Ensure clone of remote repo exists locally for giturl {{ ansible_vars_repo_url }}
  ansible.builtin.git:
    dest: "{{ managed_ansible_vars_repo_path }}"
    repo: "{{ ansible_vars_repo_url }}"
    force: true
    update: true
    accept_hostkey: yes
  when: ansible_vars_repo_url is defined

- name: Include all YAML files from the remote vars_files directory "{{ managed_ansible_vars_repo_path }}"
  ansible.builtin.include_vars:
    dir: "{{ managed_ansible_vars_repo_path }}"
    ignore_unknown_extensions: true
    extensions:
      - yml
