- name: Ensure organizations are present in AWX
  include_tasks: process_organization.yml
  loop: "{{ awx_configuration.organizations | dict2items }}"
  loop_control:
    loop_var: org_item
    label: "{{ org_item.key }}"
  register: awx_organizations