---
# this should be replaced with https://ansible-runner.readthedocs.io/en/latest/
- name: Execute ansible-galaxy collection build at project path
  command:
    argv: "{{ collection_build_args }}"
    chdir: "{{ project_path }}"
  environment:
    ANSIBLE_GALAXY_SERVER_LIST: 'stg_galaxy, galaxy'
    ANSIBLE_GALAXY_SERVER_STG_GALAXY_URL: 'https://atl-stg-anshub-01a.sec.ibm.com/api/galaxy/content/published/'
    ANSIBLE_GALAXY_SERVER_GALAXY_URL: 'https://galaxy.ansible.com'
    ANSIBLE_GALAXY_IGNORE: 'yes'
    ANSIBLE_GALAXY_SERVER_STG_GALAXY_TOKEN: "{{ lookup('file',aah_oauthtoken_path) }}"
  when:
    - rebuild_ansible_collections is defined
    - rebuild_ansible_collections|bool

- name: Execute collection_prep_add_docs at project_path
  command:
    cmd: "{{ venv_bin_path }}/collection_prep_add_docs -p . -b master"
    chdir: "{{ project_path }}"

