---
- hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: korbad.project_management.managed_git_repo       
  - name: korbad.project_management.load_vars_from_path
    vars:
      load_vars_path: "{{ managed_git_repo_path }}"
  - korbad.project_management.managed_ansible_collections
  - korbad.project_management.managed_ansible_roles
  - korbad.project_management.managed_git_repos
