---
- hosts: localhost
  vars_prompt:
  - name: git_url
    prompt: git url of user vars?
  vars:
    current_user: "{{ lookup('env','USER') }}"
  roles:
  - name: korbad.project_management.managed_user_vars