---
- name: Get git fetch {{ source_path }}
  command:
    cmd: git fetch
    chdir: "{{ source_path }}"
  register: git_fetch

- name: Get git status {{ source_path }}
  command:
    cmd: git status
    chdir: "{{ source_path }}"
  register: git_status

- name: Open vscode so the user can stage/delete changes
  include_tasks: open_vscode.yml
  when: >
    'Changes not staged for commit' in git_status.stdout
    or 'Your branch is ahead' in git_status.stdout
    or 'Untracked files' in git_status.stdout

- name: git branch
  command:
    cmd: git branch -l
    chdir: "{{ source_path }}"
  register: git_branches

- name: git branch no-merged
  command:
    cmd: git branch -l --no-merged
    chdir: "{{ source_path }}"
  register: git_branches_nomerged

- name: git diff for current branch to remote
  command:
    cmd: git diff @{u}
    chdir: "{{ source_path }}"
  register: git_diff