---
- name: Ansible Role
  include_role:
    name: managed_ansible_role
  vars:
    fully_qualified_role_name: "{{ project.fully_qualified_role_name }}"
    git_url: "{{ project.git_url }}"
  loop: "{{ managed_ansible_roles }}"
  loop_control:
    label: "{{ project.fully_qualified_role_name }}"
    loop_var: project
  when:
  - managed_ansible_roles is defined and managed_ansible_roles is iterable
