---
- name: "Perform safe-purge of git repos at {{ managed_ansible_roles_path }}"
  include_role:
    name: managed_git_repos
    tasks_from: safe_purge
  vars:
    managed_git_repos_path: "{{ managed_ansible_roles_path }}"