---
- name: Execute git status and diff checks
  include_tasks: ../check_repo.yml

- name: Open vscode so the user can stage/delete changes
  include_tasks: open_vscode.yml
  when: >
    'Changes not staged for commit' in git_status.stdout
    or 'Your branch is ahead' in git_status.stdout
    or 'Untracked files' in git_status.stdout
    or git_diff.rc != 0
