managed_rust_crates_dirname: managed_rust_crates
managed_rust_crates_path: "{{ (ansible_env.HOME, managed_rust_crates_dirname) | path_join }}"
managed_rust_crate_path: "{{ (managed_rust_crates_path, rust_crate_name) | path_join }}"
