---
- name: Ensure intermediate CA directory exists for {{ intermediate_cert_name }}
  ansible.builtin.file:
    path: "{{ managed_intermediate_ca_cert_dir_path }}"
    state: directory
    mode: "0700"

- name: Ensure intermediate CA private key exists for {{ intermediate_cert_name }}
  ansible.builtin.openssl_privatekey:
    path: "{{ intermediate_ca_key_path }}"
    size: 4096
    mode: "0600"
  register: intermediate_ca_key_result

- name: Ensure intermediate CA CSR exists for {{ intermediate_cert_name }}
  ansible.builtin.openssl_csr:
    path: "{{ intermediate_ca_csr_path }}"
    privatekey_path: "{{ intermediate_ca_key_path }}"
    common_name: "Managed Intermediate CA for {{ intermediate_cert_name }}"
    mode: "0600"

- name: Sign intermediate CA CSR ({{ intermediate_cert_name }}) with Root CA {{root_ca_cert_path}}
  ansible.builtin.openssl_certificate:
    path: "{{ intermediate_ca_cert_path }}"
    privatekey_path: "{{ intermediate_ca_key_path }}"
    csr_path: "{{ intermediate_ca_csr_path }}"
    ownca_path: "{{ root_ca_cert_path }}"
    ownca_privatekey_path: "{{ root_ca_key_path }}"
    provider: ownca
    mode: "0600"
    force: "{{ intermediate_ca_key_result is changed }}"
